/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ACommonBinaryLogicExp extends PBinaryLogicExp
{
    private PEqualityExp _equalityExp_;

    public ACommonBinaryLogicExp()
    {
    }

    public ACommonBinaryLogicExp(
        PEqualityExp _equalityExp_)
    {
        setEqualityExp(_equalityExp_);

    }
    public Object clone()
    {
        return new ACommonBinaryLogicExp(
            (PEqualityExp) cloneNode(_equalityExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommonBinaryLogicExp(this);
    }

    public PEqualityExp getEqualityExp()
    {
        return _equalityExp_;
    }

    public void setEqualityExp(PEqualityExp node)
    {
        if(_equalityExp_ != null)
        {
            _equalityExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _equalityExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_equalityExp_);
    }

    void removeChild(Node child)
    {
        if(_equalityExp_ == child)
        {
            _equalityExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_equalityExp_ == oldChild)
        {
            setEqualityExp((PEqualityExp) newChild);
            return;
        }

    }
}
