/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AEmptyLogicAndExp extends PLogicAndExp
{
    private PUnaryExp _unaryExp_;

    public AEmptyLogicAndExp()
    {
    }

    public AEmptyLogicAndExp(
        PUnaryExp _unaryExp_)
    {
        setUnaryExp(_unaryExp_);

    }
    public Object clone()
    {
        return new AEmptyLogicAndExp(
            (PUnaryExp) cloneNode(_unaryExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyLogicAndExp(this);
    }

    public PUnaryExp getUnaryExp()
    {
        return _unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(_unaryExp_ != null)
        {
            _unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_unaryExp_);
    }

    void removeChild(Node child)
    {
        if(_unaryExp_ == child)
        {
            _unaryExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

    }
}
