/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AFsmInputAlpha extends PFsmInputAlpha
{
    private TInputAlpha _inputAlpha_;
    private TEqual _equal_;
    private TLBrace _lBrace_;
    private PInputAlphaList _inputAlphaList_;
    private TRBrace _rBrace_;

    public AFsmInputAlpha()
    {
    }

    public AFsmInputAlpha(
        TInputAlpha _inputAlpha_,
        TEqual _equal_,
        TLBrace _lBrace_,
        PInputAlphaList _inputAlphaList_,
        TRBrace _rBrace_)
    {
        setInputAlpha(_inputAlpha_);

        setEqual(_equal_);

        setLBrace(_lBrace_);

        setInputAlphaList(_inputAlphaList_);

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new AFsmInputAlpha(
            (TInputAlpha) cloneNode(_inputAlpha_),
            (TEqual) cloneNode(_equal_),
            (TLBrace) cloneNode(_lBrace_),
            (PInputAlphaList) cloneNode(_inputAlphaList_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFsmInputAlpha(this);
    }

    public TInputAlpha getInputAlpha()
    {
        return _inputAlpha_;
    }

    public void setInputAlpha(TInputAlpha node)
    {
        if(_inputAlpha_ != null)
        {
            _inputAlpha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inputAlpha_ = node;
    }

    public TEqual getEqual()
    {
        return _equal_;
    }

    public void setEqual(TEqual node)
    {
        if(_equal_ != null)
        {
            _equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _equal_ = node;
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public PInputAlphaList getInputAlphaList()
    {
        return _inputAlphaList_;
    }

    public void setInputAlphaList(PInputAlphaList node)
    {
        if(_inputAlphaList_ != null)
        {
            _inputAlphaList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inputAlphaList_ = node;
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_inputAlpha_)
            + toString(_equal_)
            + toString(_lBrace_)
            + toString(_inputAlphaList_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_inputAlpha_ == child)
        {
            _inputAlpha_ = null;
            return;
        }

        if(_equal_ == child)
        {
            _equal_ = null;
            return;
        }

        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_inputAlphaList_ == child)
        {
            _inputAlphaList_ = null;
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_inputAlpha_ == oldChild)
        {
            setInputAlpha((TInputAlpha) newChild);
            return;
        }

        if(_equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(_inputAlphaList_ == oldChild)
        {
            setInputAlphaList((PInputAlphaList) newChild);
            return;
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }
}
