/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AGeEqualityLogic extends PEqualityLogic
{
    private TLGe _lGe_;

    public AGeEqualityLogic()
    {
    }

    public AGeEqualityLogic(
        TLGe _lGe_)
    {
        setLGe(_lGe_);

    }
    public Object clone()
    {
        return new AGeEqualityLogic(
            (TLGe) cloneNode(_lGe_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGeEqualityLogic(this);
    }

    public TLGe getLGe()
    {
        return _lGe_;
    }

    public void setLGe(TLGe node)
    {
        if(_lGe_ != null)
        {
            _lGe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lGe_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lGe_);
    }

    void removeChild(Node child)
    {
        if(_lGe_ == child)
        {
            _lGe_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lGe_ == oldChild)
        {
            setLGe((TLGe) newChild);
            return;
        }

    }
}
