/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ALtEqualityLogic extends PEqualityLogic
{
    private TLLt _lLt_;

    public ALtEqualityLogic()
    {
    }

    public ALtEqualityLogic(
        TLLt _lLt_)
    {
        setLLt(_lLt_);

    }
    public Object clone()
    {
        return new ALtEqualityLogic(
            (TLLt) cloneNode(_lLt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALtEqualityLogic(this);
    }

    public TLLt getLLt()
    {
        return _lLt_;
    }

    public void setLLt(TLLt node)
    {
        if(_lLt_ != null)
        {
            _lLt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lLt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lLt_);
    }

    void removeChild(Node child)
    {
        if(_lLt_ == child)
        {
            _lLt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lLt_ == oldChild)
        {
            setLLt((TLLt) newChild);
            return;
        }

    }
}
