/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ANeqEqualityLogic extends PEqualityLogic
{
    private TLNeq _lNeq_;

    public ANeqEqualityLogic()
    {
    }

    public ANeqEqualityLogic(
        TLNeq _lNeq_)
    {
        setLNeq(_lNeq_);

    }
    public Object clone()
    {
        return new ANeqEqualityLogic(
            (TLNeq) cloneNode(_lNeq_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqEqualityLogic(this);
    }

    public TLNeq getLNeq()
    {
        return _lNeq_;
    }

    public void setLNeq(TLNeq node)
    {
        if(_lNeq_ != null)
        {
            _lNeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lNeq_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lNeq_);
    }

    void removeChild(Node child)
    {
        if(_lNeq_ == child)
        {
            _lNeq_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lNeq_ == oldChild)
        {
            setLNeq((TLNeq) newChild);
            return;
        }

    }
}
