/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ANotunaryUnaryExp extends PUnaryExp
{
    private TLNot _lNot_;
    private PUnaryExp _unaryExp_;

    public ANotunaryUnaryExp()
    {
    }

    public ANotunaryUnaryExp(
        TLNot _lNot_,
        PUnaryExp _unaryExp_)
    {
        setLNot(_lNot_);

        setUnaryExp(_unaryExp_);

    }
    public Object clone()
    {
        return new ANotunaryUnaryExp(
            (TLNot) cloneNode(_lNot_),
            (PUnaryExp) cloneNode(_unaryExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotunaryUnaryExp(this);
    }

    public TLNot getLNot()
    {
        return _lNot_;
    }

    public void setLNot(TLNot node)
    {
        if(_lNot_ != null)
        {
            _lNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lNot_ = node;
    }

    public PUnaryExp getUnaryExp()
    {
        return _unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(_unaryExp_ != null)
        {
            _unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _unaryExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lNot_)
            + toString(_unaryExp_);
    }

    void removeChild(Node child)
    {
        if(_lNot_ == child)
        {
            _lNot_ = null;
            return;
        }

        if(_unaryExp_ == child)
        {
            _unaryExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lNot_ == oldChild)
        {
            setLNot((TLNot) newChild);
            return;
        }

        if(_unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

    }
}
