/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AParenExp extends PParenExp
{
    private TLPar _lPar_;
    private PPredicateLogic _predicateLogic_;
    private TRPar _rPar_;

    public AParenExp()
    {
    }

    public AParenExp(
        TLPar _lPar_,
        PPredicateLogic _predicateLogic_,
        TRPar _rPar_)
    {
        setLPar(_lPar_);

        setPredicateLogic(_predicateLogic_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AParenExp(
            (TLPar) cloneNode(_lPar_),
            (PPredicateLogic) cloneNode(_predicateLogic_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenExp(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PPredicateLogic getPredicateLogic()
    {
        return _predicateLogic_;
    }

    public void setPredicateLogic(PPredicateLogic node)
    {
        if(_predicateLogic_ != null)
        {
            _predicateLogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _predicateLogic_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_predicateLogic_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_predicateLogic_ == child)
        {
            _predicateLogic_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_predicateLogic_ == oldChild)
        {
            setPredicateLogic((PPredicateLogic) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
