/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AScopeStateList extends PStateList
{
    private PStateScope _stateScope_;

    public AScopeStateList()
    {
    }

    public AScopeStateList(
        PStateScope _stateScope_)
    {
        setStateScope(_stateScope_);

    }
    public Object clone()
    {
        return new AScopeStateList(
            (PStateScope) cloneNode(_stateScope_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScopeStateList(this);
    }

    public PStateScope getStateScope()
    {
        return _stateScope_;
    }

    public void setStateScope(PStateScope node)
    {
        if(_stateScope_ != null)
        {
            _stateScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateScope_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stateScope_);
    }

    void removeChild(Node child)
    {
        if(_stateScope_ == child)
        {
            _stateScope_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stateScope_ == oldChild)
        {
            setStateScope((PStateScope) newChild);
            return;
        }

    }
}
