/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequenceTransitionList extends PTransitionList
{
    private PTransitionList _transitionList_;
    private POneTransition _oneTransition_;

    public ASequenceTransitionList()
    {
    }

    public ASequenceTransitionList(
        PTransitionList _transitionList_,
        POneTransition _oneTransition_)
    {
        setTransitionList(_transitionList_);

        setOneTransition(_oneTransition_);

    }
    public Object clone()
    {
        return new ASequenceTransitionList(
            (PTransitionList) cloneNode(_transitionList_),
            (POneTransition) cloneNode(_oneTransition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceTransitionList(this);
    }

    public PTransitionList getTransitionList()
    {
        return _transitionList_;
    }

    public void setTransitionList(PTransitionList node)
    {
        if(_transitionList_ != null)
        {
            _transitionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _transitionList_ = node;
    }

    public POneTransition getOneTransition()
    {
        return _oneTransition_;
    }

    public void setOneTransition(POneTransition node)
    {
        if(_oneTransition_ != null)
        {
            _oneTransition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _oneTransition_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_transitionList_)
            + toString(_oneTransition_);
    }

    void removeChild(Node child)
    {
        if(_transitionList_ == child)
        {
            _transitionList_ = null;
            return;
        }

        if(_oneTransition_ == child)
        {
            _oneTransition_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_transitionList_ == oldChild)
        {
            setTransitionList((PTransitionList) newChild);
            return;
        }

        if(_oneTransition_ == oldChild)
        {
            setOneTransition((POneTransition) newChild);
            return;
        }

    }
}
