/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequenceConstraintPairList extends PConstraintPairList
{
    private PConstraintPairList _constraintPairList_;
    private PMyConstraintPair _myConstraintPair_;

    public ASequenceConstraintPairList()
    {
    }

    public ASequenceConstraintPairList(
        PConstraintPairList _constraintPairList_,
        PMyConstraintPair _myConstraintPair_)
    {
        setConstraintPairList(_constraintPairList_);

        setMyConstraintPair(_myConstraintPair_);

    }
    public Object clone()
    {
        return new ASequenceConstraintPairList(
            (PConstraintPairList) cloneNode(_constraintPairList_),
            (PMyConstraintPair) cloneNode(_myConstraintPair_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceConstraintPairList(this);
    }

    public PConstraintPairList getConstraintPairList()
    {
        return _constraintPairList_;
    }

    public void setConstraintPairList(PConstraintPairList node)
    {
        if(_constraintPairList_ != null)
        {
            _constraintPairList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _constraintPairList_ = node;
    }

    public PMyConstraintPair getMyConstraintPair()
    {
        return _myConstraintPair_;
    }

    public void setMyConstraintPair(PMyConstraintPair node)
    {
        if(_myConstraintPair_ != null)
        {
            _myConstraintPair_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myConstraintPair_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_constraintPairList_)
            + toString(_myConstraintPair_);
    }

    void removeChild(Node child)
    {
        if(_constraintPairList_ == child)
        {
            _constraintPairList_ = null;
            return;
        }

        if(_myConstraintPair_ == child)
        {
            _myConstraintPair_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_constraintPairList_ == oldChild)
        {
            setConstraintPairList((PConstraintPairList) newChild);
            return;
        }

        if(_myConstraintPair_ == oldChild)
        {
            setMyConstraintPair((PMyConstraintPair) newChild);
            return;
        }

    }
}
