/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequenceTypeList extends PTypeList
{
    private PTypeList _typeList_;
    private PMyType _myType_;

    public ASequenceTypeList()
    {
    }

    public ASequenceTypeList(
        PTypeList _typeList_,
        PMyType _myType_)
    {
        setTypeList(_typeList_);

        setMyType(_myType_);

    }
    public Object clone()
    {
        return new ASequenceTypeList(
            (PTypeList) cloneNode(_typeList_),
            (PMyType) cloneNode(_myType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceTypeList(this);
    }

    public PTypeList getTypeList()
    {
        return _typeList_;
    }

    public void setTypeList(PTypeList node)
    {
        if(_typeList_ != null)
        {
            _typeList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _typeList_ = node;
    }

    public PMyType getMyType()
    {
        return _myType_;
    }

    public void setMyType(PMyType node)
    {
        if(_myType_ != null)
        {
            _myType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myType_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_typeList_)
            + toString(_myType_);
    }

    void removeChild(Node child)
    {
        if(_typeList_ == child)
        {
            _typeList_ = null;
            return;
        }

        if(_myType_ == child)
        {
            _myType_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_typeList_ == oldChild)
        {
            setTypeList((PTypeList) newChild);
            return;
        }

        if(_myType_ == oldChild)
        {
            setMyType((PMyType) newChild);
            return;
        }

    }
}
