/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequence2StateList extends PStateList
{
    private PStateList _stateList_;
    private TComma _comma_;
    private PStateScope _stateScope_;

    public ASequence2StateList()
    {
    }

    public ASequence2StateList(
        PStateList _stateList_,
        TComma _comma_,
        PStateScope _stateScope_)
    {
        setStateList(_stateList_);

        setComma(_comma_);

        setStateScope(_stateScope_);

    }
    public Object clone()
    {
        return new ASequence2StateList(
            (PStateList) cloneNode(_stateList_),
            (TComma) cloneNode(_comma_),
            (PStateScope) cloneNode(_stateScope_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequence2StateList(this);
    }

    public PStateList getStateList()
    {
        return _stateList_;
    }

    public void setStateList(PStateList node)
    {
        if(_stateList_ != null)
        {
            _stateList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateList_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PStateScope getStateScope()
    {
        return _stateScope_;
    }

    public void setStateScope(PStateScope node)
    {
        if(_stateScope_ != null)
        {
            _stateScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateScope_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stateList_)
            + toString(_comma_)
            + toString(_stateScope_);
    }

    void removeChild(Node child)
    {
        if(_stateList_ == child)
        {
            _stateList_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_stateScope_ == child)
        {
            _stateScope_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stateList_ == oldChild)
        {
            setStateList((PStateList) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_stateScope_ == oldChild)
        {
            setStateScope((PStateScope) newChild);
            return;
        }

    }
}
