/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequenceAbbrVariableList extends PAbbrVariableList
{
    private PAbbrVariableList _abbrVariableList_;
    private POneVariablePair _oneVariablePair_;

    public ASequenceAbbrVariableList()
    {
    }

    public ASequenceAbbrVariableList(
        PAbbrVariableList _abbrVariableList_,
        POneVariablePair _oneVariablePair_)
    {
        setAbbrVariableList(_abbrVariableList_);

        setOneVariablePair(_oneVariablePair_);

    }
    public Object clone()
    {
        return new ASequenceAbbrVariableList(
            (PAbbrVariableList) cloneNode(_abbrVariableList_),
            (POneVariablePair) cloneNode(_oneVariablePair_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceAbbrVariableList(this);
    }

    public PAbbrVariableList getAbbrVariableList()
    {
        return _abbrVariableList_;
    }

    public void setAbbrVariableList(PAbbrVariableList node)
    {
        if(_abbrVariableList_ != null)
        {
            _abbrVariableList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _abbrVariableList_ = node;
    }

    public POneVariablePair getOneVariablePair()
    {
        return _oneVariablePair_;
    }

    public void setOneVariablePair(POneVariablePair node)
    {
        if(_oneVariablePair_ != null)
        {
            _oneVariablePair_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _oneVariablePair_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_abbrVariableList_)
            + toString(_oneVariablePair_);
    }

    void removeChild(Node child)
    {
        if(_abbrVariableList_ == child)
        {
            _abbrVariableList_ = null;
            return;
        }

        if(_oneVariablePair_ == child)
        {
            _oneVariablePair_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_abbrVariableList_ == oldChild)
        {
            setAbbrVariableList((PAbbrVariableList) newChild);
            return;
        }

        if(_oneVariablePair_ == oldChild)
        {
            setOneVariablePair((POneVariablePair) newChild);
            return;
        }

    }
}
