/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequence1StateList extends PStateList
{
    private PStateList _stateList_;
    private TComma _comma_;
    private PStateAlpha _stateAlpha_;

    public ASequence1StateList()
    {
    }

    public ASequence1StateList(
        PStateList _stateList_,
        TComma _comma_,
        PStateAlpha _stateAlpha_)
    {
        setStateList(_stateList_);

        setComma(_comma_);

        setStateAlpha(_stateAlpha_);

    }
    public Object clone()
    {
        return new ASequence1StateList(
            (PStateList) cloneNode(_stateList_),
            (TComma) cloneNode(_comma_),
            (PStateAlpha) cloneNode(_stateAlpha_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequence1StateList(this);
    }

    public PStateList getStateList()
    {
        return _stateList_;
    }

    public void setStateList(PStateList node)
    {
        if(_stateList_ != null)
        {
            _stateList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateList_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PStateAlpha getStateAlpha()
    {
        return _stateAlpha_;
    }

    public void setStateAlpha(PStateAlpha node)
    {
        if(_stateAlpha_ != null)
        {
            _stateAlpha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _stateAlpha_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_stateList_)
            + toString(_comma_)
            + toString(_stateAlpha_);
    }

    void removeChild(Node child)
    {
        if(_stateList_ == child)
        {
            _stateList_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_stateAlpha_ == child)
        {
            _stateAlpha_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_stateList_ == oldChild)
        {
            setStateList((PStateList) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_stateAlpha_ == oldChild)
        {
            setStateAlpha((PStateAlpha) newChild);
            return;
        }

    }
}
