/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASingleInputAlphaList extends PInputAlphaList
{
    private PMyInputAlpha _myInputAlpha_;

    public ASingleInputAlphaList()
    {
    }

    public ASingleInputAlphaList(
        PMyInputAlpha _myInputAlpha_)
    {
        setMyInputAlpha(_myInputAlpha_);

    }
    public Object clone()
    {
        return new ASingleInputAlphaList(
            (PMyInputAlpha) cloneNode(_myInputAlpha_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleInputAlphaList(this);
    }

    public PMyInputAlpha getMyInputAlpha()
    {
        return _myInputAlpha_;
    }

    public void setMyInputAlpha(PMyInputAlpha node)
    {
        if(_myInputAlpha_ != null)
        {
            _myInputAlpha_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myInputAlpha_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myInputAlpha_);
    }

    void removeChild(Node child)
    {
        if(_myInputAlpha_ == child)
        {
            _myInputAlpha_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myInputAlpha_ == oldChild)
        {
            setMyInputAlpha((PMyInputAlpha) newChild);
            return;
        }

    }
}
