/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASingleTransitionList extends PTransitionList
{
    private POneTransition _oneTransition_;

    public ASingleTransitionList()
    {
    }

    public ASingleTransitionList(
        POneTransition _oneTransition_)
    {
        setOneTransition(_oneTransition_);

    }
    public Object clone()
    {
        return new ASingleTransitionList(
            (POneTransition) cloneNode(_oneTransition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleTransitionList(this);
    }

    public POneTransition getOneTransition()
    {
        return _oneTransition_;
    }

    public void setOneTransition(POneTransition node)
    {
        if(_oneTransition_ != null)
        {
            _oneTransition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _oneTransition_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_oneTransition_);
    }

    void removeChild(Node child)
    {
        if(_oneTransition_ == child)
        {
            _oneTransition_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_oneTransition_ == oldChild)
        {
            setOneTransition((POneTransition) newChild);
            return;
        }

    }
}
