/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TConstraintPair extends Token
{
    public TConstraintPair()
    {
        super.setText("ConstraintPair");
    }

    public TConstraintPair(int line, int pos)
    {
        super.setText("ConstraintPair");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TConstraintPair(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConstraintPair(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TConstraintPair text.");
    }
}
