/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TCrlf extends Token
{
    public TCrlf()
    {
        super.setText("crlf");
    }

    public TCrlf(int line, int pos)
    {
        super.setText("crlf");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TCrlf(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCrlf(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TCrlf text.");
    }
}
