/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class THyphen extends Token
{
    public THyphen()
    {
        super.setText("-");
    }

    public THyphen(int line, int pos)
    {
        super.setText("-");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THyphen(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHyphen(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THyphen text.");
    }
}
