/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TLGt extends Token
{
    public TLGt()
    {
        super.setText("\\GT");
    }

    public TLGt(int line, int pos)
    {
        super.setText("\\GT");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLGt(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLGt(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLGt text.");
    }
}
