/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TPredicatesForState extends Token
{
    public TPredicatesForState()
    {
        super.setText("PredicatesForState");
    }

    public TPredicatesForState(int line, int pos)
    {
        super.setText("PredicatesForState");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPredicatesForState(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPredicatesForState(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPredicatesForState text.");
    }
}
