/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.parser;

import uk.ac.ucl.cs.InputMatrix.myparser.node.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTHeadPos(THeadPos node)
    {
        index = 0;
    }

    public void caseTSpace(TSpace node)
    {
        index = 1;
    }

    public void caseTCrlf(TCrlf node)
    {
        index = 2;
    }

    public void caseTLBrace(TLBrace node)
    {
        index = 3;
    }

    public void caseTRBrace(TRBrace node)
    {
        index = 4;
    }

    public void caseTArrow(TArrow node)
    {
        index = 5;
    }

    public void caseTLPar(TLPar node)
    {
        index = 6;
    }

    public void caseTRPar(TRPar node)
    {
        index = 7;
    }

    public void caseTString(TString node)
    {
        index = 8;
    }

    public void caseTComma(TComma node)
    {
        index = 9;
    }

    public void caseTHyphen(THyphen node)
    {
        index = 10;
    }

    public void caseTEqual(TEqual node)
    {
        index = 11;
    }

    public void caseTName(TName node)
    {
        index = 12;
    }

    public void caseTState(TState node)
    {
        index = 13;
    }

    public void caseTInputAlpha(TInputAlpha node)
    {
        index = 14;
    }

    public void caseTStart(TStart node)
    {
        index = 15;
    }

    public void caseTForbidden(TForbidden node)
    {
        index = 16;
    }

    public void caseTTransitionFunc(TTransitionFunc node)
    {
        index = 17;
    }

    public void caseTTrigger(TTrigger node)
    {
        index = 18;
    }

    public void caseTPriority(TPriority node)
    {
        index = 19;
    }

    public void caseTContextTypes(TContextTypes node)
    {
        index = 20;
    }

    public void caseTContextVariables(TContextVariables node)
    {
        index = 21;
    }

    public void caseTPredicateAbbr(TPredicateAbbr node)
    {
        index = 22;
    }

    public void caseTPredicatesForState(TPredicatesForState node)
    {
        index = 23;
    }

    public void caseTConstraintPair(TConstraintPair node)
    {
        index = 24;
    }

    public void caseTVariableAbbr(TVariableAbbr node)
    {
        index = 25;
    }

    public void caseTId(TId node)
    {
        index = 26;
    }

    public void caseTInt(TInt node)
    {
        index = 27;
    }

    public void caseTScopeChar(TScopeChar node)
    {
        index = 28;
    }

    public void caseTMyChar(TMyChar node)
    {
        index = 29;
    }

    public void caseTNumber(TNumber node)
    {
        index = 30;
    }

    public void caseTPrioritySettingValue(TPrioritySettingValue node)
    {
        index = 31;
    }

    public void caseTLOr(TLOr node)
    {
        index = 32;
    }

    public void caseTLAnd(TLAnd node)
    {
        index = 33;
    }

    public void caseTLNot(TLNot node)
    {
        index = 34;
    }

    public void caseTLIn(TLIn node)
    {
        index = 35;
    }

    public void caseTLGt(TLGt node)
    {
        index = 36;
    }

    public void caseTLLt(TLLt node)
    {
        index = 37;
    }

    public void caseTLEq(TLEq node)
    {
        index = 38;
    }

    public void caseTLLe(TLLe node)
    {
        index = 39;
    }

    public void caseTLNeq(TLNeq node)
    {
        index = 40;
    }

    public void caseTLGe(TLGe node)
    {
        index = 41;
    }

    public void caseTDist(TDist node)
    {
        index = 42;
    }

    public void caseEOF(EOF node)
    {
        index = 43;
    }
}
