/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ABtClients extends PBtClients
{
    private TLBrace _lBrace_;
    private PBtValueList _btValueList_;
    private TRBrace _rBrace_;

    public ABtClients()
    {
    }

    public ABtClients(
        TLBrace _lBrace_,
        PBtValueList _btValueList_,
        TRBrace _rBrace_)
    {
        setLBrace(_lBrace_);

        setBtValueList(_btValueList_);

        setRBrace(_rBrace_);

    }
    public Object clone()
    {
        return new ABtClients(
            (TLBrace) cloneNode(_lBrace_),
            (PBtValueList) cloneNode(_btValueList_),
            (TRBrace) cloneNode(_rBrace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABtClients(this);
    }

    public TLBrace getLBrace()
    {
        return _lBrace_;
    }

    public void setLBrace(TLBrace node)
    {
        if(_lBrace_ != null)
        {
            _lBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lBrace_ = node;
    }

    public PBtValueList getBtValueList()
    {
        return _btValueList_;
    }

    public void setBtValueList(PBtValueList node)
    {
        if(_btValueList_ != null)
        {
            _btValueList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _btValueList_ = node;
    }

    public TRBrace getRBrace()
    {
        return _rBrace_;
    }

    public void setRBrace(TRBrace node)
    {
        if(_rBrace_ != null)
        {
            _rBrace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rBrace_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lBrace_)
            + toString(_btValueList_)
            + toString(_rBrace_);
    }

    void removeChild(Node child)
    {
        if(_lBrace_ == child)
        {
            _lBrace_ = null;
            return;
        }

        if(_btValueList_ == child)
        {
            _btValueList_ = null;
            return;
        }

        if(_rBrace_ == child)
        {
            _rBrace_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lBrace_ == oldChild)
        {
            setLBrace((TLBrace) newChild);
            return;
        }

        if(_btValueList_ == oldChild)
        {
            setBtValueList((PBtValueList) newChild);
            return;
        }

        if(_rBrace_ == oldChild)
        {
            setRBrace((TRBrace) newChild);
            return;
        }

    }
}
