/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AEmptyRelationExp extends PRelationExp
{
    private PMyUnaryExp _myUnaryExp_;

    public AEmptyRelationExp()
    {
    }

    public AEmptyRelationExp(
        PMyUnaryExp _myUnaryExp_)
    {
        setMyUnaryExp(_myUnaryExp_);

    }
    public Object clone()
    {
        return new AEmptyRelationExp(
            (PMyUnaryExp) cloneNode(_myUnaryExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyRelationExp(this);
    }

    public PMyUnaryExp getMyUnaryExp()
    {
        return _myUnaryExp_;
    }

    public void setMyUnaryExp(PMyUnaryExp node)
    {
        if(_myUnaryExp_ != null)
        {
            _myUnaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myUnaryExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myUnaryExp_);
    }

    void removeChild(Node child)
    {
        if(_myUnaryExp_ == child)
        {
            _myUnaryExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myUnaryExp_ == oldChild)
        {
            setMyUnaryExp((PMyUnaryExp) newChild);
            return;
        }

    }
}
