/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AEmptyLogicOrExp extends PLogicOrExp
{
    private PLogicAndExp _logicAndExp_;

    public AEmptyLogicOrExp()
    {
    }

    public AEmptyLogicOrExp(
        PLogicAndExp _logicAndExp_)
    {
        setLogicAndExp(_logicAndExp_);

    }
    public Object clone()
    {
        return new AEmptyLogicOrExp(
            (PLogicAndExp) cloneNode(_logicAndExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyLogicOrExp(this);
    }

    public PLogicAndExp getLogicAndExp()
    {
        return _logicAndExp_;
    }

    public void setLogicAndExp(PLogicAndExp node)
    {
        if(_logicAndExp_ != null)
        {
            _logicAndExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _logicAndExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_logicAndExp_);
    }

    void removeChild(Node child)
    {
        if(_logicAndExp_ == child)
        {
            _logicAndExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_logicAndExp_ == oldChild)
        {
            setLogicAndExp((PLogicAndExp) newChild);
            return;
        }

    }
}
