/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AEmptyForbiddenStateList extends PForbiddenStateList
{

    public AEmptyForbiddenStateList()
    {
    }
    public Object clone()
    {
        return new AEmptyForbiddenStateList();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyForbiddenStateList(this);
    }

    public String toString()
    {
        return "";
    }

    void removeChild(Node child)
    {
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }
}
