/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AFsmPriority extends PFsmPriority
{
    private TPriority _priority_;
    private TEqual _equal_;
    private PPriorityList _priorityList_;

    public AFsmPriority()
    {
    }

    public AFsmPriority(
        TPriority _priority_,
        TEqual _equal_,
        PPriorityList _priorityList_)
    {
        setPriority(_priority_);

        setEqual(_equal_);

        setPriorityList(_priorityList_);

    }
    public Object clone()
    {
        return new AFsmPriority(
            (TPriority) cloneNode(_priority_),
            (TEqual) cloneNode(_equal_),
            (PPriorityList) cloneNode(_priorityList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFsmPriority(this);
    }

    public TPriority getPriority()
    {
        return _priority_;
    }

    public void setPriority(TPriority node)
    {
        if(_priority_ != null)
        {
            _priority_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _priority_ = node;
    }

    public TEqual getEqual()
    {
        return _equal_;
    }

    public void setEqual(TEqual node)
    {
        if(_equal_ != null)
        {
            _equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _equal_ = node;
    }

    public PPriorityList getPriorityList()
    {
        return _priorityList_;
    }

    public void setPriorityList(PPriorityList node)
    {
        if(_priorityList_ != null)
        {
            _priorityList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _priorityList_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_priority_)
            + toString(_equal_)
            + toString(_priorityList_);
    }

    void removeChild(Node child)
    {
        if(_priority_ == child)
        {
            _priority_ = null;
            return;
        }

        if(_equal_ == child)
        {
            _equal_ = null;
            return;
        }

        if(_priorityList_ == child)
        {
            _priorityList_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_priority_ == oldChild)
        {
            setPriority((TPriority) newChild);
            return;
        }

        if(_equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(_priorityList_ == oldChild)
        {
            setPriorityList((PPriorityList) newChild);
            return;
        }

    }
}
