/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AGtEqualityLogic extends PEqualityLogic
{
    private TLGt _lGt_;

    public AGtEqualityLogic()
    {
    }

    public AGtEqualityLogic(
        TLGt _lGt_)
    {
        setLGt(_lGt_);

    }
    public Object clone()
    {
        return new AGtEqualityLogic(
            (TLGt) cloneNode(_lGt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtEqualityLogic(this);
    }

    public TLGt getLGt()
    {
        return _lGt_;
    }

    public void setLGt(TLGt node)
    {
        if(_lGt_ != null)
        {
            _lGt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lGt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lGt_);
    }

    void removeChild(Node child)
    {
        if(_lGt_ == child)
        {
            _lGt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lGt_ == oldChild)
        {
            setLGt((TLGt) newChild);
            return;
        }

    }
}
