/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AInputScope extends PInputScope
{
    private TScopeChar _scopeChar_;

    public AInputScope()
    {
    }

    public AInputScope(
        TScopeChar _scopeChar_)
    {
        setScopeChar(_scopeChar_);

    }
    public Object clone()
    {
        return new AInputScope(
            (TScopeChar) cloneNode(_scopeChar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInputScope(this);
    }

    public TScopeChar getScopeChar()
    {
        return _scopeChar_;
    }

    public void setScopeChar(TScopeChar node)
    {
        if(_scopeChar_ != null)
        {
            _scopeChar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _scopeChar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_scopeChar_);
    }

    void removeChild(Node child)
    {
        if(_scopeChar_ == child)
        {
            _scopeChar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_scopeChar_ == oldChild)
        {
            setScopeChar((TScopeChar) newChild);
            return;
        }

    }
}
