/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ALeEqualityLogic extends PEqualityLogic
{
    private TLLe _lLe_;

    public ALeEqualityLogic()
    {
    }

    public ALeEqualityLogic(
        TLLe _lLe_)
    {
        setLLe(_lLe_);

    }
    public Object clone()
    {
        return new ALeEqualityLogic(
            (TLLe) cloneNode(_lLe_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeEqualityLogic(this);
    }

    public TLLe getLLe()
    {
        return _lLe_;
    }

    public void setLLe(TLLe node)
    {
        if(_lLe_ != null)
        {
            _lLe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lLe_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lLe_);
    }

    void removeChild(Node child)
    {
        if(_lLe_ == child)
        {
            _lLe_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lLe_ == oldChild)
        {
            setLLe((TLLe) newChild);
            return;
        }

    }
}
