/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AMyType extends PMyType
{
    private TLPar _lPar_;
    private PTypeAbbr _shorttypename_;
    private TComma _comma1_;
    private PTypeName _fulltypename_;
    private TComma _comma2_;
    private PRefreshRate _refreshRate_;
    private TRPar _rPar_;

    public AMyType()
    {
    }

    public AMyType(
        TLPar _lPar_,
        PTypeAbbr _shorttypename_,
        TComma _comma1_,
        PTypeName _fulltypename_,
        TComma _comma2_,
        PRefreshRate _refreshRate_,
        TRPar _rPar_)
    {
        setLPar(_lPar_);

        setShorttypename(_shorttypename_);

        setComma1(_comma1_);

        setFulltypename(_fulltypename_);

        setComma2(_comma2_);

        setRefreshRate(_refreshRate_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new AMyType(
            (TLPar) cloneNode(_lPar_),
            (PTypeAbbr) cloneNode(_shorttypename_),
            (TComma) cloneNode(_comma1_),
            (PTypeName) cloneNode(_fulltypename_),
            (TComma) cloneNode(_comma2_),
            (PRefreshRate) cloneNode(_refreshRate_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMyType(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PTypeAbbr getShorttypename()
    {
        return _shorttypename_;
    }

    public void setShorttypename(PTypeAbbr node)
    {
        if(_shorttypename_ != null)
        {
            _shorttypename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _shorttypename_ = node;
    }

    public TComma getComma1()
    {
        return _comma1_;
    }

    public void setComma1(TComma node)
    {
        if(_comma1_ != null)
        {
            _comma1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma1_ = node;
    }

    public PTypeName getFulltypename()
    {
        return _fulltypename_;
    }

    public void setFulltypename(PTypeName node)
    {
        if(_fulltypename_ != null)
        {
            _fulltypename_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _fulltypename_ = node;
    }

    public TComma getComma2()
    {
        return _comma2_;
    }

    public void setComma2(TComma node)
    {
        if(_comma2_ != null)
        {
            _comma2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma2_ = node;
    }

    public PRefreshRate getRefreshRate()
    {
        return _refreshRate_;
    }

    public void setRefreshRate(PRefreshRate node)
    {
        if(_refreshRate_ != null)
        {
            _refreshRate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _refreshRate_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_shorttypename_)
            + toString(_comma1_)
            + toString(_fulltypename_)
            + toString(_comma2_)
            + toString(_refreshRate_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_shorttypename_ == child)
        {
            _shorttypename_ = null;
            return;
        }

        if(_comma1_ == child)
        {
            _comma1_ = null;
            return;
        }

        if(_fulltypename_ == child)
        {
            _fulltypename_ = null;
            return;
        }

        if(_comma2_ == child)
        {
            _comma2_ = null;
            return;
        }

        if(_refreshRate_ == child)
        {
            _refreshRate_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_shorttypename_ == oldChild)
        {
            setShorttypename((PTypeAbbr) newChild);
            return;
        }

        if(_comma1_ == oldChild)
        {
            setComma1((TComma) newChild);
            return;
        }

        if(_fulltypename_ == oldChild)
        {
            setFulltypename((PTypeName) newChild);
            return;
        }

        if(_comma2_ == oldChild)
        {
            setComma2((TComma) newChild);
            return;
        }

        if(_refreshRate_ == oldChild)
        {
            setRefreshRate((PRefreshRate) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
