/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AParenexpPrimaryExp extends PPrimaryExp
{
    private PParenExp _parenExp_;

    public AParenexpPrimaryExp()
    {
    }

    public AParenexpPrimaryExp(
        PParenExp _parenExp_)
    {
        setParenExp(_parenExp_);

    }
    public Object clone()
    {
        return new AParenexpPrimaryExp(
            (PParenExp) cloneNode(_parenExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenexpPrimaryExp(this);
    }

    public PParenExp getParenExp()
    {
        return _parenExp_;
    }

    public void setParenExp(PParenExp node)
    {
        if(_parenExp_ != null)
        {
            _parenExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _parenExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_parenExp_);
    }

    void removeChild(Node child)
    {
        if(_parenExp_ == child)
        {
            _parenExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_parenExp_ == oldChild)
        {
            setParenExp((PParenExp) newChild);
            return;
        }

    }
}
