/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class APrimexpUnaryExp extends PUnaryExp
{
    private PPrimaryExp _primaryExp_;

    public APrimexpUnaryExp()
    {
    }

    public APrimexpUnaryExp(
        PPrimaryExp _primaryExp_)
    {
        setPrimaryExp(_primaryExp_);

    }
    public Object clone()
    {
        return new APrimexpUnaryExp(
            (PPrimaryExp) cloneNode(_primaryExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimexpUnaryExp(this);
    }

    public PPrimaryExp getPrimaryExp()
    {
        return _primaryExp_;
    }

    public void setPrimaryExp(PPrimaryExp node)
    {
        if(_primaryExp_ != null)
        {
            _primaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _primaryExp_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_primaryExp_);
    }

    void removeChild(Node child)
    {
        if(_primaryExp_ == child)
        {
            _primaryExp_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_primaryExp_ == oldChild)
        {
            setPrimaryExp((PPrimaryExp) newChild);
            return;
        }

    }
}
