/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class AScopeInputAlphaList extends PInputAlphaList
{
    private PInputScope _inputScope_;

    public AScopeInputAlphaList()
    {
    }

    public AScopeInputAlphaList(
        PInputScope _inputScope_)
    {
        setInputScope(_inputScope_);

    }
    public Object clone()
    {
        return new AScopeInputAlphaList(
            (PInputScope) cloneNode(_inputScope_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScopeInputAlphaList(this);
    }

    public PInputScope getInputScope()
    {
        return _inputScope_;
    }

    public void setInputScope(PInputScope node)
    {
        if(_inputScope_ != null)
        {
            _inputScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inputScope_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_inputScope_);
    }

    void removeChild(Node child)
    {
        if(_inputScope_ == child)
        {
            _inputScope_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_inputScope_ == oldChild)
        {
            setInputScope((PInputScope) newChild);
            return;
        }

    }
}
