/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASequence2InputAlphaList extends PInputAlphaList
{
    private PInputAlphaList _inputAlphaList_;
    private TComma _comma_;
    private PInputScope _inputScope_;

    public ASequence2InputAlphaList()
    {
    }

    public ASequence2InputAlphaList(
        PInputAlphaList _inputAlphaList_,
        TComma _comma_,
        PInputScope _inputScope_)
    {
        setInputAlphaList(_inputAlphaList_);

        setComma(_comma_);

        setInputScope(_inputScope_);

    }
    public Object clone()
    {
        return new ASequence2InputAlphaList(
            (PInputAlphaList) cloneNode(_inputAlphaList_),
            (TComma) cloneNode(_comma_),
            (PInputScope) cloneNode(_inputScope_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequence2InputAlphaList(this);
    }

    public PInputAlphaList getInputAlphaList()
    {
        return _inputAlphaList_;
    }

    public void setInputAlphaList(PInputAlphaList node)
    {
        if(_inputAlphaList_ != null)
        {
            _inputAlphaList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inputAlphaList_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PInputScope getInputScope()
    {
        return _inputScope_;
    }

    public void setInputScope(PInputScope node)
    {
        if(_inputScope_ != null)
        {
            _inputScope_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _inputScope_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_inputAlphaList_)
            + toString(_comma_)
            + toString(_inputScope_);
    }

    void removeChild(Node child)
    {
        if(_inputAlphaList_ == child)
        {
            _inputAlphaList_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_inputScope_ == child)
        {
            _inputScope_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_inputAlphaList_ == oldChild)
        {
            setInputAlphaList((PInputAlphaList) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_inputScope_ == oldChild)
        {
            setInputScope((PInputScope) newChild);
            return;
        }

    }
}
