/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASingleTriggerList extends PTriggerList
{
    private PMyTrigger _myTrigger_;

    public ASingleTriggerList()
    {
    }

    public ASingleTriggerList(
        PMyTrigger _myTrigger_)
    {
        setMyTrigger(_myTrigger_);

    }
    public Object clone()
    {
        return new ASingleTriggerList(
            (PMyTrigger) cloneNode(_myTrigger_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleTriggerList(this);
    }

    public PMyTrigger getMyTrigger()
    {
        return _myTrigger_;
    }

    public void setMyTrigger(PMyTrigger node)
    {
        if(_myTrigger_ != null)
        {
            _myTrigger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myTrigger_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myTrigger_);
    }

    void removeChild(Node child)
    {
        if(_myTrigger_ == child)
        {
            _myTrigger_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myTrigger_ == oldChild)
        {
            setMyTrigger((PMyTrigger) newChild);
            return;
        }

    }
}
