/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASinglePredicateList extends PPredicateList
{
    private PMyPredicate _myPredicate_;

    public ASinglePredicateList()
    {
    }

    public ASinglePredicateList(
        PMyPredicate _myPredicate_)
    {
        setMyPredicate(_myPredicate_);

    }
    public Object clone()
    {
        return new ASinglePredicateList(
            (PMyPredicate) cloneNode(_myPredicate_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinglePredicateList(this);
    }

    public PMyPredicate getMyPredicate()
    {
        return _myPredicate_;
    }

    public void setMyPredicate(PMyPredicate node)
    {
        if(_myPredicate_ != null)
        {
            _myPredicate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myPredicate_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myPredicate_);
    }

    void removeChild(Node child)
    {
        if(_myPredicate_ == child)
        {
            _myPredicate_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myPredicate_ == oldChild)
        {
            setMyPredicate((PMyPredicate) newChild);
            return;
        }

    }
}
