/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASingleConstraintPairList extends PConstraintPairList
{
    private PMyConstraintPair _myConstraintPair_;

    public ASingleConstraintPairList()
    {
    }

    public ASingleConstraintPairList(
        PMyConstraintPair _myConstraintPair_)
    {
        setMyConstraintPair(_myConstraintPair_);

    }
    public Object clone()
    {
        return new ASingleConstraintPairList(
            (PMyConstraintPair) cloneNode(_myConstraintPair_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleConstraintPairList(this);
    }

    public PMyConstraintPair getMyConstraintPair()
    {
        return _myConstraintPair_;
    }

    public void setMyConstraintPair(PMyConstraintPair node)
    {
        if(_myConstraintPair_ != null)
        {
            _myConstraintPair_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myConstraintPair_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myConstraintPair_);
    }

    void removeChild(Node child)
    {
        if(_myConstraintPair_ == child)
        {
            _myConstraintPair_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myConstraintPair_ == oldChild)
        {
            setMyConstraintPair((PMyConstraintPair) newChild);
            return;
        }

    }
}
