/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ASingleVariableList extends PVariableList
{
    private PMyVariable _myVariable_;

    public ASingleVariableList()
    {
    }

    public ASingleVariableList(
        PMyVariable _myVariable_)
    {
        setMyVariable(_myVariable_);

    }
    public Object clone()
    {
        return new ASingleVariableList(
            (PMyVariable) cloneNode(_myVariable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleVariableList(this);
    }

    public PMyVariable getMyVariable()
    {
        return _myVariable_;
    }

    public void setMyVariable(PMyVariable node)
    {
        if(_myVariable_ != null)
        {
            _myVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _myVariable_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_myVariable_);
    }

    void removeChild(Node child)
    {
        if(_myVariable_ == child)
        {
            _myVariable_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_myVariable_ == oldChild)
        {
            setMyVariable((PMyVariable) newChild);
            return;
        }

    }
}
