/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import java.util.*;
import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class ATriggerpriorityMyPriority extends PMyPriority
{
    private TLPar _lPar_;
    private PMyTriggerAlpha _trigger_;
    private TComma _comma_;
    private PPrioritySetting _prioritySetting_;
    private TRPar _rPar_;

    public ATriggerpriorityMyPriority()
    {
    }

    public ATriggerpriorityMyPriority(
        TLPar _lPar_,
        PMyTriggerAlpha _trigger_,
        TComma _comma_,
        PPrioritySetting _prioritySetting_,
        TRPar _rPar_)
    {
        setLPar(_lPar_);

        setTrigger(_trigger_);

        setComma(_comma_);

        setPrioritySetting(_prioritySetting_);

        setRPar(_rPar_);

    }
    public Object clone()
    {
        return new ATriggerpriorityMyPriority(
            (TLPar) cloneNode(_lPar_),
            (PMyTriggerAlpha) cloneNode(_trigger_),
            (TComma) cloneNode(_comma_),
            (PPrioritySetting) cloneNode(_prioritySetting_),
            (TRPar) cloneNode(_rPar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATriggerpriorityMyPriority(this);
    }

    public TLPar getLPar()
    {
        return _lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(_lPar_ != null)
        {
            _lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lPar_ = node;
    }

    public PMyTriggerAlpha getTrigger()
    {
        return _trigger_;
    }

    public void setTrigger(PMyTriggerAlpha node)
    {
        if(_trigger_ != null)
        {
            _trigger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _trigger_ = node;
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PPrioritySetting getPrioritySetting()
    {
        return _prioritySetting_;
    }

    public void setPrioritySetting(PPrioritySetting node)
    {
        if(_prioritySetting_ != null)
        {
            _prioritySetting_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _prioritySetting_ = node;
    }

    public TRPar getRPar()
    {
        return _rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(_rPar_ != null)
        {
            _rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _rPar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lPar_)
            + toString(_trigger_)
            + toString(_comma_)
            + toString(_prioritySetting_)
            + toString(_rPar_);
    }

    void removeChild(Node child)
    {
        if(_lPar_ == child)
        {
            _lPar_ = null;
            return;
        }

        if(_trigger_ == child)
        {
            _trigger_ = null;
            return;
        }

        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_prioritySetting_ == child)
        {
            _prioritySetting_ = null;
            return;
        }

        if(_rPar_ == child)
        {
            _rPar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(_trigger_ == oldChild)
        {
            setTrigger((PMyTriggerAlpha) newChild);
            return;
        }

        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_prioritySetting_ == oldChild)
        {
            setPrioritySetting((PPrioritySetting) newChild);
            return;
        }

        if(_rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

    }
}
