/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class Start extends Node
{
    private PSpecs _pSpecs_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PSpecs _pSpecs_,
        EOF _eof_)
    {
        setPSpecs(_pSpecs_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PSpecs) cloneNode(_pSpecs_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PSpecs getPSpecs()
    {
        return _pSpecs_;
    }

    public void setPSpecs(PSpecs node)
    {
        if(_pSpecs_ != null)
        {
            _pSpecs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pSpecs_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pSpecs_ == child)
        {
            _pSpecs_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pSpecs_ == oldChild)
        {
            setPSpecs((PSpecs) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pSpecs_) +
            toString(_eof_);
    }
}
