/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TDist extends Token
{
    public TDist()
    {
        super.setText("$Distance");
    }

    public TDist(int line, int pos)
    {
        super.setText("$Distance");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDist(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDist(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDist text.");
    }
}
