/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TLEq extends Token
{
    public TLEq()
    {
        super.setText("\\EQ");
    }

    public TLEq(int line, int pos)
    {
        super.setText("\\EQ");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLEq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLEq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLEq text.");
    }
}
