/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TLGe extends Token
{
    public TLGe()
    {
        super.setText("\\GE");
    }

    public TLGe(int line, int pos)
    {
        super.setText("\\GE");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLGe(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLGe(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLGe text.");
    }
}
