/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TLNeq extends Token
{
    public TLNeq()
    {
        super.setText("\\NEQ");
    }

    public TLNeq(int line, int pos)
    {
        super.setText("\\NEQ");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLNeq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLNeq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLNeq text.");
    }
}
