/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TLNot extends Token
{
    public TLNot()
    {
        super.setText("\\NOT");
    }

    public TLNot(int line, int pos)
    {
        super.setText("\\NOT");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLNot(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLNot(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLNot text.");
    }
}
