/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TPredicateAbbr extends Token
{
    public TPredicateAbbr()
    {
        super.setText("PredicateAbbr");
    }

    public TPredicateAbbr(int line, int pos)
    {
        super.setText("PredicateAbbr");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPredicateAbbr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPredicateAbbr(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPredicateAbbr text.");
    }
}
