/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.node;

import uk.ac.ucl.cs.InputMatrix.myparser.analysis.*;

public final class TSpace extends Token
{
    public TSpace()
    {
        super.setText("space");
    }

    public TSpace(int line, int pos)
    {
        super.setText("space");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSpace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSpace(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSpace text.");
    }
}
