/* This file was generated by SableCC (http://www.sablecc.org/). */

package uk.ac.ucl.cs.InputMatrix.myparser.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
